export type DCChargingStation = {
  id: string;
  name: string;
  provider: string;
  state: string;
  city: string;
  address: string;
  latitude: number;
  longitude: number;
  chargerType: "DC";
  connectors: Array<"CCS2" | "CHAdeMO" | "Tesla CCS2">;
  maxPowerKw: number;
  stalls: number;
  isHighwayStop: boolean;
  notes?: string;
};

export const mockDCChargingStationsMalaysia: DCChargingStation[] = [
  { id: "dc-my-kl-001", name: "Pavilion Kuala Lumpur DC Fast Charger", provider: "Tesla Supercharger", state: "Kuala Lumpur", city: "Bukit Bintang", address: "Pavilion Kuala Lumpur, 168 Jalan Bukit Bintang, Kuala Lumpur", latitude: 3.1491, longitude: 101.7134, chargerType: "DC", connectors: ["Tesla CCS2"], maxPowerKw: 250, stalls: 8, isHighwayStop: false },
  { id: "dc-my-kl-002", name: "Suria KLCC DC Charging Hub", provider: "Gentari", state: "Kuala Lumpur", city: "KLCC", address: "Suria KLCC, Kuala Lumpur City Centre, Kuala Lumpur", latitude: 3.1579, longitude: 101.7123, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 180, stalls: 4, isHighwayStop: false },
  { id: "dc-my-kl-003", name: "Mid Valley Megamall DC Charger", provider: "JomCharge", state: "Kuala Lumpur", city: "Mid Valley City", address: "Mid Valley Megamall, Lingkaran Syed Putra, Kuala Lumpur", latitude: 3.1184, longitude: 101.6779, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 120, stalls: 4, isHighwayStop: false },
  { id: "dc-my-kl-004", name: "The Gardens Mall DC Charger", provider: "ChargEV", state: "Kuala Lumpur", city: "Mid Valley City", address: "The Gardens Mall, Lingkaran Syed Putra, Kuala Lumpur", latitude: 3.1178, longitude: 101.6767, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 90, stalls: 2, isHighwayStop: false },
  { id: "dc-my-kl-005", name: "Bangsar Shopping Centre DC Charger", provider: "JomCharge", state: "Kuala Lumpur", city: "Bangsar", address: "Bangsar Shopping Centre, Jalan Maarof, Kuala Lumpur", latitude: 3.1425, longitude: 101.6672, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 120, stalls: 2, isHighwayStop: false },
  { id: "dc-my-kl-006", name: "Setapak Central DC Charger", provider: "ChargEV", state: "Kuala Lumpur", city: "Setapak", address: "Setapak Central Mall, Jalan Taman Ibu Kota, Kuala Lumpur", latitude: 3.2046, longitude: 101.7204, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 60, stalls: 2, isHighwayStop: false },
  { id: "dc-my-sgr-001", name: "Sunway Pyramid DC Fast Charger", provider: "Tesla Supercharger", state: "Selangor", city: "Subang Jaya", address: "Sunway Pyramid, Bandar Sunway, Selangor", latitude: 3.0733, longitude: 101.6072, chargerType: "DC", connectors: ["Tesla CCS2"], maxPowerKw: 250, stalls: 8, isHighwayStop: false },
  { id: "dc-my-sgr-002", name: "1 Utama Shopping Centre DC Charger", provider: "Gentari", state: "Selangor", city: "Petaling Jaya", address: "1 Utama Shopping Centre, Bandar Utama, Selangor", latitude: 3.1506, longitude: 101.6156, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 180, stalls: 4, isHighwayStop: false },
  { id: "dc-my-sgr-003", name: "IOI City Mall Putrajaya DC Charger", provider: "Tesla Supercharger", state: "Selangor", city: "Putrajaya", address: "IOI City Mall, Lebuh IRC, Putrajaya", latitude: 2.9697, longitude: 101.7136, chargerType: "DC", connectors: ["Tesla CCS2"], maxPowerKw: 250, stalls: 8, isHighwayStop: false },
  { id: "dc-my-sgr-004", name: "Setia City Mall DC Charger", provider: "JomCharge", state: "Selangor", city: "Shah Alam", address: "Setia City Mall, Setia Alam, Shah Alam, Selangor", latitude: 3.1093, longitude: 101.4597, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 120, stalls: 2, isHighwayStop: false },
  { id: "dc-my-sgr-005", name: "Gamuda Cove DC Charger", provider: "Gentari", state: "Selangor", city: "Dengkil", address: "Gamuda Cove, Persiaran Cove Sentral, Dengkil, Selangor", latitude: 2.8754, longitude: 101.6117, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 180, stalls: 4, isHighwayStop: true },
  { id: "dc-my-sgr-006", name: "Mitsui Outlet Park KLIA DC Charger", provider: "ChargEV", state: "Selangor", city: "Sepang", address: "Mitsui Outlet Park KLIA, Sepang, Selangor", latitude: 2.7375, longitude: 101.7112, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 120, stalls: 2, isHighwayStop: true },
  { id: "dc-my-sgr-007", name: "KLIA Terminal 2 DC Charger", provider: "Gentari", state: "Selangor", city: "Sepang", address: "KLIA Terminal 2, Sepang, Selangor", latitude: 2.7456, longitude: 101.7072, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 180, stalls: 4, isHighwayStop: true },
  { id: "dc-my-sgr-008", name: "Subang Parade DC Charger", provider: "JomCharge", state: "Selangor", city: "Subang Jaya", address: "Subang Parade, Jalan SS16/1, Subang Jaya, Selangor", latitude: 3.0814, longitude: 101.5859, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 90, stalls: 2, isHighwayStop: false },
  { id: "dc-my-nsn-001", name: "Seremban R&R DC Charger Northbound", provider: "Gentari", state: "Negeri Sembilan", city: "Seremban", address: "PLUS R&R Seremban Northbound, Negeri Sembilan", latitude: 2.7255, longitude: 101.9401, chargerType: "DC", connectors: ["CCS2", "CHAdeMO"], maxPowerKw: 180, stalls: 4, isHighwayStop: true },
  { id: "dc-my-nsn-002", name: "Seremban R&R DC Charger Southbound", provider: "Gentari", state: "Negeri Sembilan", city: "Seremban", address: "PLUS R&R Seremban Southbound, Negeri Sembilan", latitude: 2.7192, longitude: 101.9357, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 180, stalls: 4, isHighwayStop: true },
  { id: "dc-my-nsn-003", name: "Palm Mall Seremban DC Charger", provider: "ChargEV", state: "Negeri Sembilan", city: "Seremban", address: "Palm Mall, Jalan Sungai Ujong, Seremban", latitude: 2.7257, longitude: 101.9377, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 60, stalls: 2, isHighwayStop: false },
  { id: "dc-my-mlk-001", name: "Ayer Keroh R&R DC Charger Northbound", provider: "Gentari", state: "Melaka", city: "Ayer Keroh", address: "PLUS R&R Ayer Keroh Northbound, Melaka", latitude: 2.2728, longitude: 102.2841, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 180, stalls: 4, isHighwayStop: true },
  { id: "dc-my-mlk-002", name: "Ayer Keroh R&R DC Charger Southbound", provider: "Gentari", state: "Melaka", city: "Ayer Keroh", address: "PLUS R&R Ayer Keroh Southbound, Melaka", latitude: 2.2658, longitude: 102.2865, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 180, stalls: 4, isHighwayStop: true },
  { id: "dc-my-mlk-003", name: "Dataran Pahlawan Melaka DC Charger", provider: "ChargEV", state: "Melaka", city: "Melaka City", address: "Dataran Pahlawan Melaka Megamall, Banda Hilir, Melaka", latitude: 2.1896, longitude: 102.2501, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 90, stalls: 2, isHighwayStop: false },
  { id: "dc-my-mlk-004", name: "Freeport A'Famosa Outlet DC Charger", provider: "JomCharge", state: "Melaka", city: "Alor Gajah", address: "Freeport A'Famosa Outlet, Alor Gajah, Melaka", latitude: 2.4431, longitude: 102.2114, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 120, stalls: 2, isHighwayStop: true },
  { id: "dc-my-jhr-001", name: "Johor Premium Outlets DC Charger", provider: "Tesla Supercharger", state: "Johor", city: "Kulai", address: "Johor Premium Outlets, Indahpura, Kulai, Johor", latitude: 1.6031, longitude: 103.6242, chargerType: "DC", connectors: ["Tesla CCS2"], maxPowerKw: 250, stalls: 8, isHighwayStop: true },
  { id: "dc-my-jhr-002", name: "Mid Valley Southkey DC Charger", provider: "Gentari", state: "Johor", city: "Johor Bahru", address: "The Mall, Mid Valley Southkey, Johor Bahru", latitude: 1.5005, longitude: 103.7775, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 180, stalls: 4, isHighwayStop: false },
  { id: "dc-my-jhr-003", name: "Paradigm Mall Johor Bahru DC Charger", provider: "JomCharge", state: "Johor", city: "Johor Bahru", address: "Paradigm Mall Johor Bahru, Skudai, Johor", latitude: 1.5165, longitude: 103.6855, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 120, stalls: 2, isHighwayStop: false },
  { id: "dc-my-jhr-004", name: "R&F Mall Johor Bahru DC Charger", provider: "ChargEV", state: "Johor", city: "Johor Bahru", address: "R&F Mall, Jalan Tanjung Puteri, Johor Bahru", latitude: 1.4626, longitude: 103.7682, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 90, stalls: 2, isHighwayStop: false },
  { id: "dc-my-jhr-005", name: "Pagoh R&R DC Charger Northbound", provider: "Gentari", state: "Johor", city: "Pagoh", address: "PLUS R&R Pagoh Northbound, Johor", latitude: 2.1541, longitude: 102.7446, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 180, stalls: 4, isHighwayStop: true },
  { id: "dc-my-jhr-006", name: "Pagoh R&R DC Charger Southbound", provider: "Gentari", state: "Johor", city: "Pagoh", address: "PLUS R&R Pagoh Southbound, Johor", latitude: 2.1486, longitude: 102.7414, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 180, stalls: 4, isHighwayStop: true },
  { id: "dc-my-jhr-007", name: "Batu Pahat Mall DC Charger", provider: "ChargeSini", state: "Johor", city: "Batu Pahat", address: "Batu Pahat Mall, Jalan Kluang, Batu Pahat, Johor", latitude: 1.8561, longitude: 102.9326, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 60, stalls: 2, isHighwayStop: false },
  { id: "dc-my-prk-001", name: "Ipoh Parade DC Charger", provider: "JomCharge", state: "Perak", city: "Ipoh", address: "Ipoh Parade, Jalan Sultan Abdul Jalil, Ipoh, Perak", latitude: 4.5965, longitude: 101.0901, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 120, stalls: 2, isHighwayStop: false },
  { id: "dc-my-prk-002", name: "AEON Mall Ipoh Station 18 DC Charger", provider: "ChargEV", state: "Perak", city: "Ipoh", address: "AEON Mall Ipoh Station 18, Ipoh, Perak", latitude: 4.5261, longitude: 101.0655, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 90, stalls: 2, isHighwayStop: false },
  { id: "dc-my-prk-003", name: "Tapah R&R DC Charger Northbound", provider: "Gentari", state: "Perak", city: "Tapah", address: "PLUS R&R Tapah Northbound, Perak", latitude: 4.2054, longitude: 101.2618, chargerType: "DC", connectors: ["CCS2", "CHAdeMO"], maxPowerKw: 180, stalls: 4, isHighwayStop: true },
  { id: "dc-my-prk-004", name: "Tapah R&R DC Charger Southbound", provider: "Gentari", state: "Perak", city: "Tapah", address: "PLUS R&R Tapah Southbound, Perak", latitude: 4.2013, longitude: 101.2587, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 180, stalls: 4, isHighwayStop: true },
  { id: "dc-my-prk-005", name: "Taiping Mall DC Charger", provider: "ChargeSini", state: "Perak", city: "Taiping", address: "Taiping Mall, Jalan Tupai, Taiping, Perak", latitude: 4.8519, longitude: 100.7416, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 60, stalls: 2, isHighwayStop: false },
  { id: "dc-my-png-001", name: "Gurney Plaza DC Charger", provider: "Tesla Supercharger", state: "Penang", city: "George Town", address: "Gurney Plaza, Persiaran Gurney, George Town, Penang", latitude: 5.4381, longitude: 100.3099, chargerType: "DC", connectors: ["Tesla CCS2"], maxPowerKw: 250, stalls: 8, isHighwayStop: false },
  { id: "dc-my-png-002", name: "Queensbay Mall DC Charger", provider: "Gentari", state: "Penang", city: "Bayan Lepas", address: "Queensbay Mall, Bayan Lepas, Penang", latitude: 5.3334, longitude: 100.3065, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 180, stalls: 4, isHighwayStop: false },
  { id: "dc-my-png-003", name: "Design Village Penang DC Charger", provider: "JomCharge", state: "Penang", city: "Batu Kawan", address: "Design Village Outlet Mall, Batu Kawan, Penang", latitude: 5.2355, longitude: 100.4386, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 120, stalls: 2, isHighwayStop: true },
  { id: "dc-my-png-004", name: "IKEA Batu Kawan DC Charger", provider: "ChargEV", state: "Penang", city: "Batu Kawan", address: "IKEA Batu Kawan, Aspen Vision City, Penang", latitude: 5.2328, longitude: 100.4389, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 90, stalls: 2, isHighwayStop: true },
  { id: "dc-my-kdh-001", name: "Aman Central Alor Setar DC Charger", provider: "JomCharge", state: "Kedah", city: "Alor Setar", address: "Aman Central, Lebuhraya Darul Aman, Alor Setar, Kedah", latitude: 6.1248, longitude: 100.3678, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 120, stalls: 2, isHighwayStop: false },
  { id: "dc-my-kdh-002", name: "Gurun R&R DC Charger Northbound", provider: "Gentari", state: "Kedah", city: "Gurun", address: "PLUS R&R Gurun Northbound, Kedah", latitude: 5.8297, longitude: 100.4806, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 180, stalls: 4, isHighwayStop: true },
  { id: "dc-my-kdh-003", name: "Gurun R&R DC Charger Southbound", provider: "Gentari", state: "Kedah", city: "Gurun", address: "PLUS R&R Gurun Southbound, Kedah", latitude: 5.8239, longitude: 100.4776, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 180, stalls: 4, isHighwayStop: true },
  { id: "dc-my-kdh-004", name: "Langkawi Kuah DC Charger", provider: "ChargEV", state: "Kedah", city: "Kuah", address: "Kuah Town, Langkawi, Kedah", latitude: 6.3168, longitude: 99.8515, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 60, stalls: 2, isHighwayStop: false },
  { id: "dc-my-pls-001", name: "Kangar DC Charger", provider: "ChargeSini", state: "Perlis", city: "Kangar", address: "Kangar Town Centre, Perlis", latitude: 6.4414, longitude: 100.1986, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 60, stalls: 2, isHighwayStop: false },
  { id: "dc-my-phg-001", name: "Genting Highlands Premium Outlets DC Charger", provider: "Tesla Supercharger", state: "Pahang", city: "Genting Highlands", address: "Genting Highlands Premium Outlets, Pahang", latitude: 3.3958, longitude: 101.7805, chargerType: "DC", connectors: ["Tesla CCS2"], maxPowerKw: 250, stalls: 8, isHighwayStop: true },
  { id: "dc-my-phg-002", name: "Kuantan City Mall DC Charger", provider: "JomCharge", state: "Pahang", city: "Kuantan", address: "Kuantan City Mall, Jalan Putra Square, Kuantan, Pahang", latitude: 3.8168, longitude: 103.3317, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 120, stalls: 2, isHighwayStop: false },
  { id: "dc-my-phg-003", name: "East Coast Mall Kuantan DC Charger", provider: "ChargEV", state: "Pahang", city: "Kuantan", address: "East Coast Mall, Jalan Putra Square, Kuantan, Pahang", latitude: 3.8182, longitude: 103.3257, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 90, stalls: 2, isHighwayStop: false },
  { id: "dc-my-phg-004", name: "Temerloh R&R DC Charger", provider: "Gentari", state: "Pahang", city: "Temerloh", address: "R&R Temerloh, East Coast Expressway, Pahang", latitude: 3.4582, longitude: 102.4221, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 180, stalls: 4, isHighwayStop: true },
  { id: "dc-my-trg-001", name: "KTCC Mall Kuala Terengganu DC Charger", provider: "JomCharge", state: "Terengganu", city: "Kuala Terengganu", address: "KTCC Mall, Muara Selatan, Kuala Terengganu", latitude: 5.3356, longitude: 103.1408, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 120, stalls: 2, isHighwayStop: false },
  { id: "dc-my-trg-002", name: "Mesra Mall Kerteh DC Charger", provider: "ChargEV", state: "Terengganu", city: "Kerteh", address: "Mesra Mall, Kerteh, Terengganu", latitude: 4.5086, longitude: 103.4492, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 60, stalls: 2, isHighwayStop: true },
  { id: "dc-my-kel-001", name: "AEON Mall Kota Bharu DC Charger", provider: "ChargeSini", state: "Kelantan", city: "Kota Bharu", address: "AEON Mall Kota Bharu, Lembah Sireh, Kota Bharu", latitude: 6.1168, longitude: 102.2373, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 60, stalls: 2, isHighwayStop: false },
  { id: "dc-my-kel-002", name: "Kota Bharu City Centre DC Charger", provider: "JomCharge", state: "Kelantan", city: "Kota Bharu", address: "Kota Bharu City Centre, Kelantan", latitude: 6.1254, longitude: 102.2381, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 90, stalls: 2, isHighwayStop: false },
  { id: "dc-my-sbh-001", name: "Imago Shopping Mall Kota Kinabalu DC Charger", provider: "ChargEV", state: "Sabah", city: "Kota Kinabalu", address: "Imago Shopping Mall, Kota Kinabalu, Sabah", latitude: 5.9701, longitude: 116.0661, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 60, stalls: 2, isHighwayStop: false },
  { id: "dc-my-sbh-002", name: "Suria Sabah DC Charger", provider: "JomCharge", state: "Sabah", city: "Kota Kinabalu", address: "Suria Sabah Shopping Mall, Kota Kinabalu, Sabah", latitude: 5.9879, longitude: 116.0783, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 90, stalls: 2, isHighwayStop: false },
  { id: "dc-my-sbh-003", name: "Sandakan Harbour Mall DC Charger", provider: "ChargeSini", state: "Sabah", city: "Sandakan", address: "Harbour Mall Sandakan, Sabah", latitude: 5.8394, longitude: 118.1173, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 60, stalls: 2, isHighwayStop: false },
  { id: "dc-my-sbh-004", name: "Tawau City DC Charger", provider: "Mock Network", state: "Sabah", city: "Tawau", address: "Tawau City Centre, Sabah", latitude: 4.2447, longitude: 117.8912, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 60, stalls: 2, isHighwayStop: false },
  { id: "dc-my-swk-001", name: "The Spring Kuching DC Charger", provider: "JomCharge", state: "Sarawak", city: "Kuching", address: "The Spring Shopping Mall, Kuching, Sarawak", latitude: 1.5275, longitude: 110.3692, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 90, stalls: 2, isHighwayStop: false },
  { id: "dc-my-swk-002", name: "Vivacity Megamall Kuching DC Charger", provider: "ChargEV", state: "Sarawak", city: "Kuching", address: "Vivacity Megamall, Kuching, Sarawak", latitude: 1.5265, longitude: 110.3981, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 90, stalls: 2, isHighwayStop: false },
  { id: "dc-my-swk-003", name: "Bintang Megamall Miri DC Charger", provider: "ChargeSini", state: "Sarawak", city: "Miri", address: "Bintang Megamall, Miri, Sarawak", latitude: 4.3995, longitude: 113.9914, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 60, stalls: 2, isHighwayStop: false },
  { id: "dc-my-swk-004", name: "Sibu Town Square DC Charger", provider: "Mock Network", state: "Sarawak", city: "Sibu", address: "Sibu Town Square, Sibu, Sarawak", latitude: 2.2876, longitude: 111.8305, chargerType: "DC", connectors: ["CCS2"], maxPowerKw: 60, stalls: 2, isHighwayStop: false },
];
